language: perl
services:
  - redis-server
perl:
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
env:
  - REDIS_VERSION=3.0.5
  - REDIS_VERSION=2.8.23
  - REDIS_VERSION=3.0.5 LC_ALL=ja_JP.UTF-8
  - REDIS_VERSION=2.8.23 LC_ALL=ja_JP.UTF-8
before_install:
  - sudo apt-get update && sudo apt-get --reinstall install -qq language-pack-en language-pack-ja
install:
  - wget https://github.com/antirez/redis/archive/$REDIS_VERSION.tar.gz && tar xzf $REDIS_VERSION.tar.gz && make -C redis-$REDIS_VERSION
  - cpanm --notest Minilla Test::CPAN::Meta Test::Pod Test::MinimumVersion::Fast
  - cpanm --quiet --installdeps --notest .
script:
  - PATH=$PWD/redis-$REDIS_VERSION/src:$PATH redis-server --version
  - PATH=$PWD/redis-$REDIS_VERSION/src:$PATH minil test --all
sudo: true
