language: perl
matrix:
  include:
  - perl: "5.30"
  - perl: "5.28"
  - perl: "5.26"
  - perl: "5.24"
  - perl: "5.22"
  - perl: "5.20"
    dist: trusty
  - perl: "5.18"
    dist: trusty
  - perl: "5.16"
    dist: trusty
  - perl: "5.14"
    dist: trusty
  - perl: "5.12"
    dist: trusty
  - perl: "5.10"
    dist: trusty
env:
  - REDIS_VERSION=5.0.5
  - REDIS_VERSION=4.0.14
  - REDIS_VERSION=3.2.13
  - REDIS_VERSION=2.8.24
os:
  - linux
# Unfortunately, perl in osx is currently broken.
#  - osx
env:
  - REDIS_VERSION=5.0.5 TEST_LANG=en_US.UTF-8
  - REDIS_VERSION=4.0.14 TEST_LANG=en_US.UTF-8
  - REDIS_VERSION=3.2.13 TEST_LANG=en_US.UTF-8
  - REDIS_VERSION=2.8.24 TEST_LANG=en_US.UTF-8
  - REDIS_VERSION=4.0.14 TEST_LANG=ja_JP.UTF-8
addons:
  apt:
    packages:
      - language-pack-ja
cache:
  directories:
  - redis-$REDIS_VERSION
  - extlib
install:
  - test -e redis-$REDIS_VERSION/src/redis-server || ( wget https://github.com/antirez/redis/archive/$REDIS_VERSION.tar.gz && tar xzf $REDIS_VERSION.tar.gz && make -C redis-$REDIS_VERSION )
  - cpanm -L extlib --quiet --notest Minilla Test::CPAN::Meta Test::Pod Test::MinimumVersion::Fast
  - cpanm -L extlib --quiet --with-develop --installdeps --notest .
script:
  - PATH=$PWD/redis-$REDIS_VERSION/src:$PATH redis-server --version
  - PERL5LIB=$PWD/extlib/lib/perl5:$PERL5LIB PATH=$PWD/redis-$REDIS_VERSION/src:$PATH LC_ALL=$TEST_LANG ./extlib/bin/minil test --all
