language: perl
perl:
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
os:
  - linux
  - osx
env:
  - REDIS_VERSION=3.0.5
  - REDIS_VERSION=2.8.23
before_install:
  - curl -L http://install.perlbrew.pl | bash
  - source ~/perl5/perlbrew/etc/bashrc
  - perlbrew install $TRAVIS_PERL_VERSION && perlbrew use $TRAVIS_PERL_VERSION
install:
  - wget https://github.com/antirez/redis/archive/$REDIS_VERSION.tar.gz && tar xzf $REDIS_VERSION.tar.gz && make -C redis-$REDIS_VERSION
  - cpanm --notest Minilla Test::CPAN::Meta Test::Pod Test::MinimumVersion::Fast
  - cpanm --quiet --installdeps --notest .
script:
  - PATH=$PWD/redis-$REDIS_VERSION/src:$PATH redis-server --version
  - PATH=$PWD/redis-$REDIS_VERSION/src:$PATH minil test --all
sudo: false
